### ISSUE TITLE
Sending direct messages doesn't work

### ISSUE THREAD

**Issue by farmdawgnation** [DanielaSfregola/twitter4s#119]
Sending direct messages doesn't work because the rest client attempts to use the Get verb instead of the post verb.

**Comment by farmdawgnation** [comment]
Ah, ignore me. This bug appears to have been fixed since 4.2.... it just hasn't been released yet hehe. Any chance there's another release coming soon? :angel:

**Comment by DanielaSfregola** [comment]
Hi @farmdawgnation! Thanks for raising this bug -- I have realised my mistake when doing some refactoring for the next major release.

I am preparing a major release that I hope to finish in a couple of weeks -- so hopefully it should not be too long before another release (lots of improvements there!).

That being said, there are 2 ways of sending direct messages:
1) `createDirectMessage` inside the `TwitterDirectMessageClient` -- the one that you spotted is broken in 4.2 [Twitter docs on the endpoint [here](https://dev.twitter.com/rest/reference/post/direct_messages/new)]
2) `createDirectMessageAsTweet` inside the `TwitterStatusClient` -- [Twitter docs on the endpoint [here](https://dev.twitter.com/rest/reference/post/statuses/update)]

There are some (minor) differences between these two endpoints, but hopefully using endpoint 2) until 1) is fixed in the next release is an acceptable temporary workaround.

Cheers

**Comment by DanielaSfregola** [comment]
For future reference, this bug has been fixed by commit https://github.com/DanielaSfregola/twitter4s/commit/d2c6d8fe45098ae5f851ca0140983d5d47685a54

**Comment by DanielaSfregola** [comment]
This is now available in twitter4s 5.0
