### ISSUE TITLE
Several logging improvements

### ISSUE THREAD

**Issue by DanielaSfregola** [DanielaSfregola/twitter4s#138]
For some reason we use scalalogging for logging purposes (see [here](https://github.com/DanielaSfregola/twitter4s/blob/6c0e4602fc10bd10dd6e9e1f1c99ecc5d16beb21/src/main/scala/com/danielasfregola/twitter4s/util/Logger.scala))

Sometimes we use LazyLogging, but people may expect we use akka logging.

- Unify the way logs are handled 
- make it easy for people to change the log level
- update twitter4s-demo to show an example on how the logging should work

**Comment by dmitraver** [comment]
@DanielaSfregola hi, I might take this one.

**Comment by Gaarv** [comment]
I will look into it tomorrow. I would vote for keeping scalalogging as doesnt get in the way of any akka log configuration and easy to setup with logback.

- [ ] Unify logs
- [ ] ability to change log level easily
- [ ] update twitter4s-demo

logback.xml was added to twitter4s.g8, so that will be the opportunity to add it in twitter4s-demo and explain the usage.

**Comment by DanielaSfregola** [comment]
Thanks @Gaarv! I think it is a great idea 👍

**Comment by DanielaSfregola** [comment]
Completed by #172, closing
