### ISSUE TITLE
Scala Steward: why do you not like us anymore?

### ISSUE THREAD

**Issue by zzvara** [DanielaSfregola/twitter4s#322]
@DanielaSfregola It would be useful to bump dependency versions more seamlessly and to keep the project up-to-date.

**Comment by DanielaSfregola** [comment]
Hi @zzvara,
this project has been using Scala Steward for quite some time now - see https://github.com/scala-steward-org/repos/blob/master/repos-github.md.

However, I can see your confusion: The bot has not been doing any PR for 23 days - which is weird!

I'll see if I can figure out why this is the case. (Changing the title of this issue)

**Comment by DanielaSfregola** [comment]
Ok, I have found a few issues related to our travis configuration - they are not fixed. See https://github.com/DanielaSfregola/twitter4s/pull/324

Not sure if they could have caused the ScalaSteward issues - I have asked support on their Gitter channel.
Hopefully, either Scala Steward will come back or they will suggest what is wrong on Gitter

**Comment by DanielaSfregola** [comment]
Ok got a reply on Gitter: no errors in the logs from the Scala Steward bot running on OS projects.
But Thomas has the following suggestion:

"""
Frank S. Thomas @fthomas 11:24
@DanielaSfregola I don't see any errors in the logs. Could it be the case that newer versions dropped 2.11 support and you are still supporting 2.11? In this cases Scala Steward do not propose new updates
"""

...I'll investigate further!

**Comment by DanielaSfregola** [comment]
Ok, mystery solved!

If I compile our code using scala 2.11.8 is not able to find the Akka version for it (I guess they dropped the support for it): 
```
[error]   not found: /Users/danielasfregola/.ivy2/local/com.typesafe.akka/akka-actor_2.11/2.6.8/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.11/2.6.8/akka-actor_2.11-2.6.8.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/typesafe/akka/akka-actor_2.11/2.6.8/akka-actor_2.11-2.6.8.pom
[error]   not found: https://jcenter.bintray.com/com/typesafe/akka/akka-actor_2.11/2.6.8/akka-actor_2.11-2.6.8.pom
```

We should have detected this in CI when the PR was created - but unfortunately, this wasn't the case because our CI configs were not working as expected.

Scala Steward is indeed smart, and it will not create a PR for a version not supporting one of your scala versions (since that will break things)! I'll drop scala 2.11 before as part of the major release.

Cheers,
Daniela
