### ISSUE TITLE
v7.1 Release Date Question

### ISSUE THREAD

**Issue by aburkhalter512** [DanielaSfregola/twitter4s#332]
Not sure where to best ask this question, but when is v7.1 getting released? Are you waiting for more changes to come in?

**Comment by DanielaSfregola** [comment]
HI @aburkhalter512,
so far we only have your PR - we should wait for more changes before releasing.

We can release a SNAPSHOT version for people to try things out - usually only for 2.13.
Would using a SNAPSHOT version be an acceptable compromise? What scala version are you using so that I can ensure we have a SNAPSHOT version for it? 

Cheers,
Daniela

**Comment by aburkhalter512** [comment]
Using a snapshot version would work great for us! Could you publish the 2.12 version?

Thanks for the quick response.

**Comment by DanielaSfregola** [comment]
Ok, I have just published 7.1-SNAPSHOT for both scala 2.12 and 2.13 - give it a try!

Make sure to follow the instructions on how to use SNAPSHOT versions at https://github.com/DanielaSfregola/twitter4s#snapshot-versions: you will need add a resolver in your sbt configuration.

Cheers,
Daniela

**Comment by DanielaSfregola** [comment]
I am going to assume you were able to use the SNAPSHOT version.
Please, let me know if this is not the case and I'll reopen the ticket
